### ISSUE TITLE
怎么安装rff库？

### ISSUE THREAD

**Issue by hellomijia** [Kaslanarian/PySVM#3]

**Comment by Kaslanarian** [comment]
你好，rff的接口是笔者自己编写的，rff.py里是实现方法，只需要几行代码就可以搞定

**Comment by hellomijia** [comment]
可以分享一下嘛？会在论文中提及引用您的模型，如果您不愿意也可以，为打扰到您感到抱歉




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kaslanarian/PySVM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月24日(星期二) 中午12:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kaslanarian/PySVM] 怎么安装rff库？ (Issue #3)





 
你好，rff的接口是笔者自己编写的，rff.py里是实现方法，只需要几行代码就可以搞定

**Comment by Kaslanarian** [comment]
可参考 https://welts.xyz/2021/10/30/fourier_kernel/ 和 https://welts.xyz/2021/11/05/rrf_svm/

**Comment by hellomijia** [comment]
thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Welt ***@***.***&gt;; 
发送时间: 2022年5月24日(星期二) 下午5:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Kaslanarian/PySVM] 怎么安装rff库？ (Issue #3)





 
可参考 https://welts.xyz/2021/10/30/fourier_kernel/ 和 https://welts.xyz/2021/11/05/rrf_svm/
