### ISSUE TITLE
保存模型

### ISSUE THREAD

**Issue by Huang-th** [Kaslanarian/PySVM#4]
使用lambda表达式进行运算不利于模型的保存的。若使用joblib等工具保存模型，需要将lambda表达式重写为类成员方法。使用dill工具保存内核状态可以解决这一问题，但这是有风险的。

**Comment by Kaslanarian** [comment]
十分感谢你的建议。lambda表达式是笔者为了让模型支持sklearn的网格调参而使用的一个取巧的方法。PySVM主要目的是复现LIBSVM的算法，所以没考虑到模型存取等话题。笔者近期恰好有花时间重构代码的想法，所以再次感谢你的建议。
