### ISSUE TITLE
Solver的working_set_select中i和j的选取

### ISSUE THREAD

**Issue by oahcnauygnid** [Kaslanarian/PySVM#5]
为什么Solver的working_set_select中i和j的选取都采用了1阶的方法了呢？libsvm好像都是用的1阶加2阶，也就是NuSolver的working_set_select？

**Comment by Kaslanarian** [comment]
确实，我之前实现了一阶+二阶的变量选择，但是发现效果和一阶并没有显著差别，反而增加了计算时间，所以i和j都用了一阶选择。

**Comment by oahcnauygnid** [comment]
我记得FCL05那篇论文《Working Set Selection Using Second Order Information for Training Support Vector Machines
》有分析一阶+二阶的变量选择的优点，说比一阶+一阶的变量选择快，我翻了下最早的commit，有这么一段注掉了
`
        # candidate_j = [t for t in Ilow if -self.y[t] * self.grad[t] < m]
        # target = [
        #     -(m + self.y[t] * self.grad[t])**2 /
        #     (self.Q[i, i] + self.Q[t, t] - 2 * self.Q[i, t])
        #     for t in candidate_j
        # ]
        # j = candidate_j[target.index(min(target))]
`，有没有可能用并行化的写法会好一些？

**Comment by Kaslanarian** [comment]
论文中的“好”指的是收敛更快，即需要更少的迭代次数。我在当时实验中发现python的列表查找（也就是你列出的代码）比较耗时。在迭代次数少+单次迭代时间长，和迭代次数多+单次迭代时间短之间，我选择了后者。我同意你的观点，如果将上面的代码全部用numpy去重写，或许时间会缩短。

**Comment by oahcnauygnid** [comment]
有没有可能改了试试？或者说我下面这样写已经可以用了

```python
def working_set_select(self):
        Iup = np.argwhere(
            np.logical_or(
                np.logical_and(self.alpha < self.C, self.y > 0),
                np.logical_and(self.alpha > 0, self.y < 0),
            )).flatten()
        Ilow = np.argwhere(
            np.logical_or(
                np.logical_and(self.alpha < self.C, self.y < 0),
                np.logical_and(self.alpha > 0, self.y > 0),
            )).flatten()

        find_fail = False
        try:
            i = Iup[np.argmax(self.neg_y_grad[Iup])]
            # j = Ilow[np.argmin(self.neg_y_grad[Ilow])]
            **m = max({-self.y[j] * self.neg_y_grad[j] for j in Iup})
            candidate_j = [t for t in Ilow if -self.y[t] * self.neg_y_grad[t] < m]
            target = [
                -(m + self.y[t] * self.neg_y_grad[t])**2 /
                (self.Q[i, i] + self.Q[t, t] - 2 * self.Q[i, t])
                for t in candidate_j
            ]
            j = candidate_j[target.index(min(target))]**
        except:
            find_fail = True

        if find_fail or self.neg_y_grad[i] - self.neg_y_grad[j] < self.tol:
            return -1, -1
        return i, j
```

**Comment by Kaslanarian** [comment]
你对`neg_y_grad`理解有点偏差，我按照二阶算法写了一个更快的代码，你可以参考一下，试一下效果：

```python
i = Iup[np.argmax(self.neg_y_grad[Iup])]
m = self.neg_y_grad[i] # 不需要再求max, neg_y_grad就是-y·grad，不需要再乘-y
candidate_j = Ilow[self.neg_y_grad[Ilow] < m] # 并行化，这样写更快
target = -(m - self.neg_y_grad[candidate_j])**2 / \
       (self.Q[i, i] + self.Q[i, candidate_j] - 2 * self.Q[candidate_j, candidate_j]) # 并行化，这种写法是不带缓存机制的

j = candidate_j[np.argmin(target)] # 并行化
```

**Comment by oahcnauygnid** [comment]
好的，我试试，感谢

**Comment by Kaslanarian** [comment]
你用的是LinearSVC吗？LinearSVC用的是liblinear的算法（更快），sklearn里面只有SVC和NuSVC用的是libsvm的算法，建议用SVC然后用同样的kernel对比一下。此外提醒一下，按我们的写法，模型的cache_size定义成0，才会调用2阶选择的算法，对比才有效，所以15s的时间有不少是浪费在计算核矩阵上了。

**Comment by oahcnauygnid** [comment]
使用是相同的参数设置，sklearn是
```python
    rbf_svm = SVC(kernel="rbf", C=1.0, gamma = 'scale', max_iter=300, tol=1e-5)
```
这里也用的相同的设置，我还没有使用cache_size，就参数选择问题来看，目前的结论应该就是在小数据集上(1阶+2阶)速度比(1阶+1阶)更慢一些，并没有体现出优势

和sklearn对比，我另提一个issue吧
